### ISSUE TITLE
Added the store address - got 5 * ID 9029

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#115]
I've set up WooCommerce and from the settings I've added the new address (Street name, city, country etc). The plugin reported 5 events with ID 9029, seems like an event ID for each entry I've added.

![image](https://user-images.githubusercontent.com/3965050/152542459-de1109b0-dcc5-4963-a028-55953531fa7f.png)

This is more of an edge care rather than the norm, since in most cases the user would only change one line and not all the entries. But curious, is there an efficient way how we can better handle this?

**Comment by DannyWPWS** [comment]
Iv been digging into this and think I have found a very simple solution! Basically the issue was all of these fields are seperate options and we have no way of knowing how many have been changed when processing etc

BUT, once we know "something" has changed, if we just wait a few milliseconds before triggering the event we can wait for ALL the options to update and only fire 1 based on the old/new address in full

I didnt know about this till now but this PHP function popped up https://www.php.net/manual/en/function.sleep.php and it seems to so very very well, so much so im suspicious so will talk to Martin about it

If its ok to use, Im certain this tasty little function can be put to use elsewhere too!!
